# This file created by conda-build 3.12.1
# meta.yaml template originally from:
# /opt/recipe, last modified Fri Aug 24 03:03:38 2018
# ------------------------------------------------

package:
    name: perl-business-isbn
    version: '3.004'
source:
    sha256: 31754acd57bf0c3d4762003d784bce4a0af6832a725336e219fb2988b6fb831e
    url: https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Business-ISBN-3.004.tar.gz
build:
    number: '0'
    string: pl526_0
requirements:
    host:
        - libgcc-ng 7.2.0 hdf63c60_3
        - perl 5.26.2 h470a237_0
        - perl-business-isbn-data 20140910.003 pl526_0
        - perl-carp 1.38 pl526_1
        - perl-data-dumper 2.161 pl526_2
        - perl-encode 2.88 pl526_1
        - perl-exporter 5.72 pl526_1
        - perl-extutils-makemaker 7.34 pl526_2
        - perl-parent 0.236 pl526_1
    run:
        - perl >=5.26.2,<5.26.3.0a0
        - perl-business-isbn-data
test:
    imports:
        - Business::ISBN
        - Business::ISBN10
        - Business::ISBN13
about:
    home: https://github.com/briandfoy/business-isbn
    license: artistic_2
    summary: work with International Standard Book Numbers
extra:
    copy_test_source_files: true
    final: true
