# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /opt/recipe, last modified Wed Aug  8 09:33:15 2018
# ------------------------------------------------

package:
    name: perl-lwp-protocol-https
    version: '6.07'
source:
    sha256: 522cc946cf84a1776304a5737a54b8822ec9e79b264d0ba0722a70473dbfb9e7
    url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/LWP-Protocol-https-6.07.tar.gz
build:
    number: '4'
    string: pl526_4
requirements:
    host:
        - ca-certificates 2018.4.16 0
        - libgcc-ng 7.2.0 hdf63c60_3
        - openssl 1.0.2o h470a237_1
        - perl 5.26.2 h470a237_0
        - perl-digest-hmac 1.03 pl526_2
        - perl-encode-locale 1.05 pl526h470a237_5
        - perl-file-listing 6.04 pl526_1
        - perl-html-parser 3.72 pl526_3
        - perl-html-tagset 3.20 pl526_2
        - perl-http-cookies 6.01 pl526_1
        - perl-http-daemon 6.01 pl526_1
        - perl-http-date 6.02 pl526_2
        - perl-http-message 6.11 pl526_1
        - perl-http-negotiate 6.01 pl526_1
        - perl-io-html 1.001 pl526_2
        - perl-io-socket-ssl 2.024 pl526_1
        - perl-libwww-perl 6.15 pl526_1
        - perl-lwp-mediatypes 6.02 pl526_2
        - perl-mime-base64 3.15 pl526_1
        - perl-mozilla-ca 20160104 pl526_2
        - perl-net-http 6.09 pl526_1
        - perl-net-ssleay 1.84 pl526h9dad42d_1
        - perl-ntlm 1.09 pl526_3
        - perl-socket 2.027 pl526_1
        - perl-test-requiresinternet 0.05 pl526_0
        - perl-uri 1.71 pl526_3
        - perl-www-robotrules 6.02 pl526_2
        - perl-xsloader 0.24 pl526_0
        - zlib 1.2.11 h470a237_3
    run:
        - perl >=5.26.2,<5.26.3.0a0
        - perl-io-socket-ssl
        - perl-libwww-perl
        - perl-mozilla-ca
        - perl-net-http
        - perl-test-requiresinternet
test:
    imports:
        - LWP::Protocol::https
about:
    home: https://metacpan.org/pod/LWP::Protocol::https
    license: Perl
    summary: Provide https support for LWP::UserAgent
extra:
    copy_test_source_files: true
    final: true
