# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Feb 12 18:46:11 2020
# ------------------------------------------------

package:
    name: pcre
    version: '8.44'
source:
    patches:
        - 0001-Define-snprintf-for-old-VS.patch
    sha256: aecafd4af3bd0f3935721af77b889d9024b2e01d96b58471bd91a3063fb47728
    url: https://ftp.pcre.org/pub/pcre/pcre-8.44.tar.gz
build:
    number: '0'
    run_exports:
        - pcre >=8.44,<9.0a0
    string: he1b5a44_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - binutils_impl_linux-64 2.33.1 h53a641e_8
        - binutils_linux-64 2.33.1 h9595d00_16
        - gcc_impl_linux-64 7.3.0 hd420e75_5
        - gcc_linux-64 7.3.0 h553295d_16
        - gxx_impl_linux-64 7.3.0 hdf63c60_5
        - gxx_linux-64 7.3.0 h553295d_16
        - ld_impl_linux-64 2.33.1 h53a641e_8
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - libtool 2.4.6 h14c3975_1002
        - make 4.2.1 h14c3975_2004
        - pkg-config 0.29.2 h516909a_1006
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
test:
    commands:
        - pcre-config --version
        - pcregrep --help
        - pcretest --help
        - test -f "${PREFIX}/include/pcre.h"
        - test -f "${PREFIX}/include/pcre_scanner.h"
        - test -f "${PREFIX}/include/pcre_stringpiece.h"
        - test -f "${PREFIX}/include/pcrecpp.h"
        - test -f "${PREFIX}/include/pcrecpparg.h"
        - test -f "${PREFIX}/include/pcreposix.h"
        - test -f "${PREFIX}/lib/libpcre.a"
        - test -f "${PREFIX}/lib/libpcre${SHLIB_EXT}"
        - test -f "${PREFIX}/lib/libpcrecpp.a"
        - test -f "${PREFIX}/lib/libpcrecpp${SHLIB_EXT}"
        - test -f "${PREFIX}/lib/libpcreposix.a"
        - test -f "${PREFIX}/lib/libpcreposix${SHLIB_EXT}"
about:
    home: http://www.pcre.org/
    license: BSD 3-Clause
    license_file: LICENCE
    summary: Regular expression pattern matching using the same syntax and semantics
        as Perl 5.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - ocefpaf
        - saraedum
        - scopatz
        - sebastian-luna-valero
