# This file created by conda-build 3.19.2
# ------------------------------------------------

package:
    name: _openmp_mutex
    version: 4.5
source:
    path: /home/conda/recipe_root
build:
    number: 14
    run_exports:
        strong:
            - _openmp_mutex >=4.5
    string: 1_gnu
requirements:
    host:
        - libgomp 7.5.0 h24d8f2e_14
    run:
        - _libgcc_mutex 0.1 conda_forge
        - libgomp >=7.5.0
    run_constrained:
        - openmp_impl 9999
test:
    commands:
        - test -f ${PREFIX}/lib/libgomp.so.1
        - test `readlink ${PREFIX}/lib/libgomp.so.1` == "libgomp.so.1.0.0"
about:
    home: https://github.com/conda-forge/ctng-compilers-feedstock
    license: BSD-3-Clause
    license_file: LICENSE
    summary: OpenMP Implementation Mutex
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - beckermr
        - isuruf
