# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jun  1 18:04:55 2020
# ------------------------------------------------

package:
    name: python
    version: 3.7.6
source:
    -   md5: c08fbee72ad5c2c95b0f4e44bf6fd72c
        patches:
            - patches/0002-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
            - patches/0003-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
            - patches/0004-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
            - patches/0005-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
            - patches/0006-Support-cross-compiling-byte-code.patch
            - patches/0007-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
            - patches/0008-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
            - patches/0009-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
            - patches/0010-Win32-Do-not-download-externals.patch
            - patches/0011-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch
            - patches/0012-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
            - patches/0013-Disable-new-dtags-in-unixccompiler.py.patch
            - patches/0014-Fix-cross-compilation-on-Debian-based-distros.patch
            - patches/0015-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
            - patches/0016-Unvendor-openssl.patch
            - patches/0017-Unvendor-sqlite3.patch
            - patches/0018-venv-Revert-a-change-from-https-github.com-python-cp.patch
            - patches/0020-Use-ranlib-from-env-if-env-variable-is-set.patch
        url: https://www.python.org/ftp/python/3.7.6/Python-3.7.6.tar.xz
build:
    detect_binary_files_with_prefix: true
    ignore_run_exports:
        - bzip2
        - libgcc-ng
    number: '6'
    run_exports:
        noarch:
            - python
        weak:
            - python_abi 3.7.* *_cp37m
    string: cpython_h8356626_6
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - binutils_impl_linux-64 2.34 h53a641e_4
        - binutils_linux-64 2.34 hc952b39_20
        - gcc_impl_linux-64 7.5.0 hd420e75_6
        - gcc_linux-64 7.5.0 h09487f9_20
        - gxx_impl_linux-64 7.5.0 hdf63c60_6
        - gxx_linux-64 7.5.0 h09487f9_20
        - ld_impl_linux-64 2.34 h53a641e_4
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - libuuid-cos6-x86_64 2.17.2 h22b9525_0
        - libuuid-devel-cos6-x86_64 2.17.2 0
        - libx11-common-cos6-x86_64 1.6.4 h023ea50_0
        - libx11-cos6-x86_64 1.6.4 h64a1553_0
        - libx11-devel-cos6-x86_64 1.6.4 hb9851ce_0
        - make 4.3 h516909a_0
        - patch 2.7.6 h14c3975_1001
        - pkg-config 0.29.2 h516909a_1006
        - sysroot_linux-64 2.12 h3a0023d_5
        - xorg-x11-proto-devel-cos6-x86_64 7.7 h8d4a98b_0
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - bzip2 1.0.8 h516909a_2
        - ca-certificates 2020.4.5.1 hecc5488_0
        - ld_impl_linux-64 2.34 h53a641e_4
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1g h516909a_0
        - readline 8.0 hf8c457e_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - xz 5.2.5 h516909a_0
        - zlib 1.2.11 h516909a_1006
    run:
        - ld_impl_linux-64
        - libffi >=3.2.1,<3.3.0a0
        - libgcc-ng >=7.5.0
        - libstdcxx-ng >=7.5.0
        - openssl >=1.1.1g,<1.1.2a
        - readline >=8.0,<9.0a0
        - sqlite >=3.30.1,<4.0a0
        - tk >=8.6.10,<8.7.0a0
        - xz >=5.2.5,<5.3.0a0
        - zlib >=1.2.11,<1.3.0a0
    run_constrained:
        - python_abi 3.7.* *_cp37m
test:
    commands:
        - python -V
        - python3 -V
        - 2to3 -h
        - pydoc -h
        - python3-config --help
        - python -c "import sys; files = [f for f in sys.argv[2:] if b' -partition=none'
            in open(f, 'rb').read()]; assert len(files) == 0, files" ${PREFIX}/lib/*/*.py
        - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
        - _CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
            python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
        - for f in ${CONDA_PREFIX}/lib/python*/_sysconfig*.py; do echo "Checking $f:";
            if [[ `rg @ $f` ]]; then echo "FAILED ON $f"; cat $f; exit 1; fi; done
        - pushd tests
        - pushd distutils
        - python setup.py install -v -v
        - python -c "import foobar"
        - popd
        - pushd distutils.cext
        - python setup.py install -v -v
        - python -c "import greet; greet.greet('Python user')" | rg "Hello Python"
        - popd
        - pushd prefix-replacement
        - bash build-and-test.sh
        - popd
        - pushd cmake
        - cmake -GNinja -DPY_VER=3.7.6
        - popd
        - popd
    files:
        - tests/cmake/*
        - tests/cython/*
        - tests/distutils.cext/*
        - tests/distutils/*
        - tests/prefix-replacement/*
    requires:
        - cmake
        - cython
        - gcc_linux-64 7.*
        - gxx_linux-64 7.*
        - ninja
        - ripgrep
        - setuptools
about:
    description: 'Python is a widely used high-level, general-purpose, interpreted,
        dynamic

        programming language. Its design philosophy emphasizes code

        readability, and its syntax allows programmers to express concepts in

        fewer lines of code than would be possible in languages such as C++ or

        Java. The language provides constructs intended to enable clear programs

        on both a small and large scale.

        '
    dev_url: https://docs.python.org/devguide/
    doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
    doc_url: https://www.python.org/doc/versions/
    home: http://www.python.org/
    license: Python-2.0
    license_file: LICENSE
    summary: General purpose programming language
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
        - scopatz
