{% set name = "googleapis-common-protos" %}
  {% set version = "1.51.0" %}
  {% set sha256 = "013c91704279119150e44ef770086fdbba158c1f978a6402167d47d5409e226e" %}

package:
  name: {{ name|lower }}-feedstock
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: True  # [win and vc<14]

requirements:
  host:
    - python
    - pip >=18.1
    - setuptools >=34.0.0

outputs:
  - name: {{ name }}
    build:
      script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --verbose"
      skip: True  # [win and vc<14]
    requirements:
      host:
        - python
        - pip >=18.1
        - protobuf >=3.6.0
        - setuptools >=34.0.0
      run:
        - python
        - protobuf
    test:
      imports:
        - google.api
        - google.api.annotations_pb2
        - google.api.auth_pb2
        - google.api.backend_pb2
        - google.api.billing_pb2
        - google.api.client_pb2
        - google.api.config_change_pb2
        - google.api.consumer_pb2
        - google.api.context_pb2
        - google.api.control_pb2
        - google.api.distribution_pb2
        - google.api.documentation_pb2
        - google.api.endpoint_pb2
        - google.api.field_behavior_pb2
        - google.api.http_pb2
        - google.api.httpbody_pb2
        - google.api.label_pb2
        - google.api.launch_stage_pb2
        - google.api.log_pb2
        - google.api.logging_pb2
        - google.api.metric_pb2
        - google.api.monitored_resource_pb2
        - google.api.monitoring_pb2
        - google.api.quota_pb2
        - google.api.resource_pb2
        - google.api.service_pb2
        - google.api.source_info_pb2
        - google.api.system_parameter_pb2
        - google.api.usage_pb2
        - google.longrunning
        - google.longrunning.operations_pb2
        - google.longrunning.operations_proto
        - google.longrunning.operations_proto_pb2
        - google.protobuf
        - google.protobuf.any_pb2
        - google.protobuf.any_test_pb2
        - google.protobuf.api_pb2
        - google.protobuf.compiler
        - google.protobuf.compiler.plugin_pb2
        - google.protobuf.descriptor
        - google.protobuf.descriptor_database
        - google.protobuf.descriptor_pb2
        - google.protobuf.descriptor_pool
        - google.protobuf.duration_pb2
        - google.protobuf.empty_pb2
        - google.protobuf.field_mask_pb2
        - google.protobuf.internal
        - google.protobuf.internal.any_test_pb2
        - google.protobuf.internal.api_implementation
        - google.protobuf.internal.containers
        - google.protobuf.internal.decoder
        - google.protobuf.internal.descriptor_database_test
        - google.protobuf.internal.descriptor_pool_test
        - google.protobuf.internal.descriptor_pool_test1_pb2
        - google.protobuf.internal.descriptor_pool_test2_pb2
        - google.protobuf.internal.descriptor_test
        - google.protobuf.internal.encoder
        - google.protobuf.internal.enum_type_wrapper
        - google.protobuf.internal.factory_test1_pb2
        - google.protobuf.internal.factory_test2_pb2
        - google.protobuf.internal.file_options_test_pb2
        - google.protobuf.internal.generator_test
        - google.protobuf.internal.import_test_package
        - google.protobuf.internal.import_test_package.inner_pb2
        - google.protobuf.internal.import_test_package.outer_pb2
        - google.protobuf.internal.json_format_test
        - google.protobuf.internal.message_factory_test
        - google.protobuf.internal.message_listener
        - google.protobuf.internal.message_set_extensions_pb2
        - google.protobuf.internal.message_test
        - google.protobuf.internal.missing_enum_values_pb2
        - google.protobuf.internal.more_extensions_dynamic_pb2
        - google.protobuf.internal.more_extensions_pb2
        - google.protobuf.internal.more_messages_pb2
        - google.protobuf.internal.no_package_pb2
        - google.protobuf.internal.packed_field_test_pb2
        - google.protobuf.internal.proto_builder_test
        - google.protobuf.internal.python_message
        - google.protobuf.internal.reflection_test
        - google.protobuf.internal.service_reflection_test
        - google.protobuf.internal.symbol_database_test
        - google.protobuf.internal.test_bad_identifiers_pb2
        - google.protobuf.internal.test_util
        - google.protobuf.internal.testing_refleaks
        - google.protobuf.internal.text_encoding_test
        - google.protobuf.internal.text_format_test
        - google.protobuf.internal.type_checkers
        - google.protobuf.internal.unknown_fields_test
        - google.protobuf.internal.well_known_types
        - google.protobuf.internal.well_known_types_test
        - google.protobuf.internal.wire_format
        - google.protobuf.internal.wire_format_test
        - google.protobuf.json_format
        - google.protobuf.map_proto2_unittest_pb2
        - google.protobuf.map_unittest_pb2
        - google.protobuf.message
        - google.protobuf.message_factory
        - google.protobuf.proto_builder
        - google.protobuf.pyext
        - google.protobuf.pyext.python_pb2
        - google.protobuf.reflection
        - google.protobuf.service
        - google.protobuf.service_reflection
        - google.protobuf.source_context_pb2
        - google.protobuf.struct_pb2
        - google.protobuf.symbol_database
        - google.protobuf.test_messages_proto2_pb2
        - google.protobuf.test_messages_proto3_pb2
        - google.protobuf.text_encoding
        - google.protobuf.text_format
        - google.protobuf.timestamp_pb2
        - google.protobuf.type_pb2
        - google.protobuf.util
        - google.protobuf.util.json_format_proto3_pb2
        - google.protobuf.wrappers_pb2
        - google.rpc
        - google.rpc.code_pb2
        - google.rpc.error_details_pb2
        - google.rpc.status_pb2
        - google.type
        - google.type.calendar_period_pb2
        - google.type.color_pb2
        - google.type.date_pb2
        - google.type.dayofweek_pb2
        - google.type.expr_pb2
        - google.type.fraction_pb2
        - google.type.latlng_pb2
        - google.type.money_pb2
        - google.type.postal_address_pb2
        - google.type.quaternion_pb2
        - google.type.timeofday_pb2

  - name: {{ name }}-grpc
    build:
      skip: True  # [win and vc<14]
    requirements:
      host:
        - python
        - grpcio >=1.0.0
      run:
        - {{ pin_subpackage(name, min_pin='x.x', max_pin='x.x') }}
        - grpcio
    test:
      imports:
        - google.api
        - google.api.annotations_pb2
        - google.api.auth_pb2
        - google.api.backend_pb2
        - google.api.billing_pb2
        - google.api.client_pb2
        - google.api.config_change_pb2
        - google.api.consumer_pb2
        - google.api.context_pb2
        - google.api.control_pb2
        - google.api.distribution_pb2
        - google.api.documentation_pb2
        - google.api.endpoint_pb2
        - google.api.field_behavior_pb2
        - google.api.http_pb2
        - google.api.httpbody_pb2
        - google.api.label_pb2
        - google.api.launch_stage_pb2
        - google.api.log_pb2
        - google.api.logging_pb2
        - google.api.metric_pb2
        - google.api.monitored_resource_pb2
        - google.api.monitoring_pb2
        - google.api.quota_pb2
        - google.api.resource_pb2
        - google.api.service_pb2
        - google.api.source_info_pb2
        - google.api.system_parameter_pb2
        - google.api.usage_pb2
        - google.longrunning
        - google.longrunning.operations_grpc
        - google.longrunning.operations_grpc_pb2
        - google.longrunning.operations_pb2
        - google.longrunning.operations_proto
        - google.longrunning.operations_proto_pb2
        - google.protobuf
        - google.protobuf.any_pb2
        - google.protobuf.any_test_pb2
        - google.protobuf.api_pb2
        - google.protobuf.compiler
        - google.protobuf.compiler.plugin_pb2
        - google.protobuf.descriptor
        - google.protobuf.descriptor_database
        - google.protobuf.descriptor_pb2
        - google.protobuf.descriptor_pool
        - google.protobuf.duration_pb2
        - google.protobuf.empty_pb2
        - google.protobuf.field_mask_pb2
        - google.protobuf.internal
        - google.protobuf.internal.any_test_pb2
        - google.protobuf.internal.api_implementation
        - google.protobuf.internal.containers
        - google.protobuf.internal.decoder
        - google.protobuf.internal.descriptor_database_test
        - google.protobuf.internal.descriptor_pool_test
        - google.protobuf.internal.descriptor_pool_test1_pb2
        - google.protobuf.internal.descriptor_pool_test2_pb2
        - google.protobuf.internal.descriptor_test
        - google.protobuf.internal.encoder
        - google.protobuf.internal.enum_type_wrapper
        - google.protobuf.internal.factory_test1_pb2
        - google.protobuf.internal.factory_test2_pb2
        - google.protobuf.internal.file_options_test_pb2
        - google.protobuf.internal.generator_test
        - google.protobuf.internal.import_test_package
        - google.protobuf.internal.import_test_package.inner_pb2
        - google.protobuf.internal.import_test_package.outer_pb2
        - google.protobuf.internal.json_format_test
        - google.protobuf.internal.message_factory_test
        - google.protobuf.internal.message_listener
        - google.protobuf.internal.message_set_extensions_pb2
        - google.protobuf.internal.message_test
        - google.protobuf.internal.missing_enum_values_pb2
        - google.protobuf.internal.more_extensions_dynamic_pb2
        - google.protobuf.internal.more_extensions_pb2
        - google.protobuf.internal.more_messages_pb2
        - google.protobuf.internal.no_package_pb2
        - google.protobuf.internal.packed_field_test_pb2
        - google.protobuf.internal.proto_builder_test
        - google.protobuf.internal.python_message
        - google.protobuf.internal.reflection_test
        - google.protobuf.internal.service_reflection_test
        - google.protobuf.internal.symbol_database_test
        - google.protobuf.internal.test_bad_identifiers_pb2
        - google.protobuf.internal.test_util
        - google.protobuf.internal.testing_refleaks
        - google.protobuf.internal.text_encoding_test
        - google.protobuf.internal.text_format_test
        - google.protobuf.internal.type_checkers
        - google.protobuf.internal.unknown_fields_test
        - google.protobuf.internal.well_known_types
        - google.protobuf.internal.well_known_types_test
        - google.protobuf.internal.wire_format
        - google.protobuf.internal.wire_format_test
        - google.protobuf.json_format
        - google.protobuf.map_proto2_unittest_pb2
        - google.protobuf.map_unittest_pb2
        - google.protobuf.message
        - google.protobuf.message_factory
        - google.protobuf.proto_builder
        - google.protobuf.pyext
        - google.protobuf.pyext.python_pb2
        - google.protobuf.reflection
        - google.protobuf.service
        - google.protobuf.service_reflection
        - google.protobuf.source_context_pb2
        - google.protobuf.struct_pb2
        - google.protobuf.symbol_database
        - google.protobuf.test_messages_proto2_pb2
        - google.protobuf.test_messages_proto3_pb2
        - google.protobuf.text_encoding
        - google.protobuf.text_format
        - google.protobuf.timestamp_pb2
        - google.protobuf.type_pb2
        - google.protobuf.util
        - google.protobuf.util.json_format_proto3_pb2
        - google.protobuf.wrappers_pb2
        - google.rpc
        - google.rpc.code_pb2
        - google.rpc.error_details_pb2
        - google.rpc.status_pb2
        - google.type
        - google.type.calendar_period_pb2
        - google.type.color_pb2
        - google.type.date_pb2
        - google.type.dayofweek_pb2
        - google.type.expr_pb2
        - google.type.fraction_pb2
        - google.type.latlng_pb2
        - google.type.money_pb2
        - google.type.postal_address_pb2
        - google.type.quaternion_pb2
        - google.type.timeofday_pb2
        - grpc
        - grpc.beta
        - grpc.framework.common
        - grpc.framework.interfaces.face
    about:
      home: https://github.com/googleapis/googleapis
      license: Apache-2.0
      license_file: LICENSE
      license_family: APACHE
      summary: Common protobufs used in Google APIs
      description: |
        {{ name }}-grpc installs {{ name }} and the grpc extra requirements.

        This repository contains the original interface definitions of public
        Google APIs that support both REST and gRPC protocols. Reading the original
        interface definitions can provide a better understanding of Google APIs and
        help you to utilize them more efficiently. You can also use these definitions
        with open source tools to generate client libraries, documentation,
        and other artifacts.

        **Deprecated Python Versions**

        Python == 2.7
        - Python 2.7 support will be removed on January 1, 2020.
        - protobuf does not support Visual C++ 2008, windows py27 package not available

      doc_url: https://github.com/googleapis/googleapis/blob/master/README.md
      dev_url: https://github.com/googleapis/googleapis

about:
  home: https://github.com/googleapis/googleapis
  license: Apache 2.0
  license_file: LICENSE
  license_family: APACHE
  summary: Common protobufs used in Google APIs
  description: |
    This package does not include the grpc extra requirements.

    This repository contains the original interface definitions of public
    Google APIs that support both REST and gRPC protocols. Reading the original
    interface definitions can provide a better understanding of Google APIs and
    help you to utilize them more efficiently. You can also use these definitions
    with open source tools to generate client libraries, documentation,
    and other artifacts.

    **Deprecated Python Versions**

    Python == 2.7
    - Python 2.7 support will be removed on January 1, 2020.
    - protobuf does not support Visual C++ 2008, windows py27 package not available

  doc_url: https://github.com/googleapis/googleapis/blob/master/README.md
  dev_url: https://github.com/googleapis/googleapis

extra:
  recipe-maintainers:
    - BrentDorsey
    - leahecole
    - parthea
    - tswast
