# This file created by conda-build 3.12.1
# meta.yaml template originally from:
# /opt/recipe, last modified Mon Aug 27 09:00:55 2018
# ------------------------------------------------

package:
    name: perl-time-local
    version: '1.28'
source:
    sha256: 9278b9e5cc99dcbb0fd27a43e914828b59685601edae082889b5ee7266afe10e
    url: https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Time-Local-1.28.tar.gz
build:
    number: '1'
    string: pl526_1
requirements:
    host:
        - libgcc-ng 7.2.0 hdf63c60_3
        - perl 5.26.2 h470a237_0
        - perl-carp 1.38 pl526_1
        - perl-constant 1.33 pl526_1
        - perl-data-dumper 2.161 pl526_2
        - perl-encode 2.88 pl526_1
        - perl-exporter 5.72 pl526_1
        - perl-extutils-makemaker 7.34 pl526_2
        - perl-parent 0.236 pl526_1
    run:
        - perl >=5.26.2,<5.26.3.0a0
        - perl-carp
        - perl-constant
        - perl-exporter
        - perl-parent
test:
    imports:
        - Time::Local
about:
    home: http://metacpan.org/release/Time-Local
    license: perl_5
    summary: Efficiently compute time from local and GMT time
extra:
    copy_test_source_files: true
    final: true
