# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /opt/recipe, last modified Sun Aug 30 12:16:20 2020
# ------------------------------------------------

package:
    name: ncbi-ngs-sdk
    version: 2.10.4
source:
    patches:
        - patch
    sha256: 6f5db2269c6afc8e51a50fbcab9c63f4b1d6b69e483c6acb40d8f9e52f8282b1
    url: https://github.com/ncbi/ngs/archive/2.10.4.tar.gz
build:
    number: '1'
    string: h3e72335_1
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - binutils_impl_linux-64 2.34 h2122c62_9
        - binutils_linux-64 2.34 h47ac705_27
        - gcc_impl_linux-64 7.5.0 hda68d29_13
        - gcc_linux-64 7.5.0 hf34d7eb_27
        - gxx_impl_linux-64 7.5.0 h64c220c_13
        - gxx_linux-64 7.5.0 ha781d05_27
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - ld_impl_linux-64 2.34 hc38a660_9
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libstdcxx-ng 9.3.0 hdf63c60_16
        - sysroot_linux-64 2.12 h77966d4_13
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - icu 67.1 he1b5a44_0
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libiconv 1.16 h516909a_0
        - libstdcxx-ng 9.3.0 hdf63c60_16
        - libxml2 2.9.10 h68273f3_2
        - perl 5.26.2 h516909a_1006
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1009
    run:
        - libgcc-ng >=7.5.0
        - libiconv >=1.16,<1.17.0a0
        - libstdcxx-ng >=7.5.0
        - libxml2 >=2.9.10,<2.10.0a0
test:
    commands:
        - test -e ${PREFIX}/lib64/libngs-sdk.so
about:
    home: https://github.com/ncbi/ngs
    license: Public Domain
    summary: NGS is a new, domain-specific API for accessing reads, alignments and
        pileups produced from Next Generation Sequencing.
extra:
    copy_test_source_files: true
    final: true
