# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Sep 10 13:28:45 2019
# ------------------------------------------------

package:
    name: pyqt
    version: 5.9.2
source:
    patches:
        - 0003-configure.patch
    sha1: 058c5b37981b515cc4e16faa04a4a6d8892cdaa9
    url: http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.9.2/PyQt5_gpl-5.9.2.tar.gz
build:
    number: '4'
    run_exports: pyqt >=5.9.2,<5.10.0a0
    string: py37hcca6a23_4
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - alsa-lib-cos6-x86_64 1.1.0 h6d2b67b_0
        - alsa-lib-devel-cos6-x86_64 1.1.0 hd867495_0
        - atk-cos6-x86_64 1.30.0 he7c67e7_0
        - atk-devel-cos6-x86_64 1.30.0 h9bddbf2_0
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - cairo-cos6-x86_64 1.8.8 had002bf_0
        - cairo-devel-cos6-x86_64 1.8.8 h8bd0bf0_0
        - fontconfig-cos6-x86_64 2.8.0 he5a27ec_0
        - fontconfig-devel-cos6-x86_64 2.8.0 hdc0f659_0
        - freetype-cos6-x86_64 2.3.11 hda26ef6_0
        - freetype-devel-cos6-x86_64 2.3.11 h781713c_0
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - gdk-pixbuf2-cos6-x86_64 2.24.1 h9eee21e_0
        - gdk-pixbuf2-devel-cos6-x86_64 2.24.1 haf2bbbe_0
        - glib2-cos6-x86_64 2.28.8 h1a821f5_0
        - glib2-devel-cos6-x86_64 2.28.8 hda010f4_0
        - gtk2-cos6-x86_64 2.24.23 h08a0018_0
        - gtk2-devel-cos6-x86_64 2.24.23 h22b3bcd_0
        - gtkmm24-cos6-x86_64 2.18.2 h76adaa3_0
        - gtkmm24-devel-cos6-x86_64 2.18.2 ha7ccc1c_0
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_8
        - libdrm-cos6-x86_64 2.4.65 hd39d64f_0
        - libdrm-devel-cos6-x86_64 2.4.65 h5701c1a_0
        - libgcc-ng 9.1.0 hdf63c60_0
        - libselinux-cos6-x86_64 2.0.94 hc7b3062_0
        - libselinux-devel-cos6-x86_64 2.0.94 h87dd427_0
        - libsepol-cos6-x86_64 2.0.41 h6e2433f_0
        - libsepol-devel-cos6-x86_64 2.0.41 h5bbff73_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libthai-cos6-x86_64 0.1.12 hf1f4b97_0
        - libx11-common-cos6-x86_64 1.6.4 h023ea50_0
        - libx11-cos6-x86_64 1.6.4 h64a1553_0
        - libx11-devel-cos6-x86_64 1.6.4 hb9851ce_0
        - libxau-cos6-x86_64 1.0.6 h4888106_0
        - libxau-devel-cos6-x86_64 1.0.6 hf5ff492_0
        - libxcb-cos6-x86_64 1.12 h6fd0490_0
        - libxcomposite-cos6-x86_64 0.4.3 h496ddd6_0
        - libxcomposite-devel-cos6-x86_64 0.4.3 h7370af7_0
        - libxcursor-cos6-x86_64 1.1.14 h4710796_0
        - libxcursor-devel-cos6-x86_64 1.1.14 h84fcfe3_0
        - libxdamage-cos6-x86_64 1.1.3 h8e310ee_0
        - libxext-cos6-x86_64 1.3.3 hc47956f_0
        - libxext-devel-cos6-x86_64 1.3.3 hf6a4bb0_0
        - libxfixes-cos6-x86_64 5.0.3 h3a64028_0
        - libxi-cos6-x86_64 1.7.8 h5354da0_0
        - libxi-devel-cos6-x86_64 1.7.8 hda042b6_0
        - libxrandr-cos6-x86_64 1.5.1 h9e6466e_0
        - libxrandr-devel-cos6-x86_64 1.5.1 h5fb6d88_0
        - libxrender-cos6-x86_64 0.9.10 h41db5cd_0
        - libxrender-devel-cos6-x86_64 0.9.10 ha8151bf_0
        - libxscrnsaver-cos6-x86_64 1.2.2 h54af3ee_0
        - libxscrnsaver-devel-cos6-x86_64 1.2.2 h6740434_0
        - libxtst-cos6-x86_64 1.2.3 hefb1821_0
        - libxtst-devel-cos6-x86_64 1.2.3 heca503c_0
        - libxxf86vm-cos6-x86_64 1.1.3 h3cd9653_0
        - mesa-dri-drivers-cos6-x86_64 11.0.7 h6ae8bd2_0
        - mesa-dri1-drivers-cos6-x86_64 7.11 hd08e721_0
        - mesa-libegl-cos6-x86_64 11.0.7 1
        - mesa-libegl-devel-cos6-x86_64 11.0.7 h2b7a4b1_0
        - mesa-libgbm-cos6-x86_64 11.0.7 0
        - mesa-libgl-cos6-x86_64 11.0.7 h045e36e_0
        - mesa-libgl-devel-cos6-x86_64 11.0.7 h5a2c0ac_0
        - pango-cos6-x86_64 1.28.1 h53c42d8_0
        - pango-devel-cos6-x86_64 1.28.1 hf23b437_0
        - pciutils-devel-cos6-x86_64 3.1.10 h99ed674_0
        - pciutils-libs-cos6-x86_64 3.1.10 hb902eda_0
        - pixman-cos6-x86_64 0.32.8 h7062e45_0
        - pixman-devel-cos6-x86_64 0.32.8 h92a7580_0
        - pkg-config 0.29.2 h14c3975_1005
        - pkgconfig-cos6-x86_64 0.23 h07b4811_0
        - xorg-x11-proto-devel-cos6-x86_64 7.7 h8d4a98b_0
    host:
        - _libgcc_mutex 0.1 main
        - bzip2 1.0.8 h516909a_1
        - ca-certificates 2019.6.16 hecc5488_0
        - dbus 1.13.6 he372182_0
        - expat 2.2.5 he1b5a44_1003
        - fontconfig 2.13.1 h86ecdb6_1001
        - freetype 2.10.0 he983fc9_1
        - gettext 0.19.8.1 hc5be6a0_1002
        - glib 2.58.3 h6f030ca_1002
        - gst-plugins-base 1.14.5 h0935bb2_0
        - gstreamer 1.14.5 h36ae1b5_0
        - icu 64.2 he1b5a44_1
        - jpeg 9c h14c3975_1001
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libiconv 1.15 h516909a_1005
        - libpng 1.6.37 hed695b0_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libuuid 2.32.1 h14c3975_1000
        - libxcb 1.13 h14c3975_1002
        - libxml2 2.9.9 hee79883_5
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - pcre 8.41 hf484d3e_1003
        - pthread-stubs 0.4 h14c3975_1001
        - python 3.7.3 h33d41f4_1
        - qt 5.9.7 h0c104cb_3
        - readline 8.0 hf8c457e_0
        - sip 4.19.8 py37hf484d3e_1000
        - sqlite 3.29.0 hcee41ef_1
        - tk 8.6.9 hed695b0_1002
        - xorg-libxau 1.0.9 h14c3975_0
        - xorg-libxdmcp 1.1.3 h516909a_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1006
    run:
        - dbus >=1.13.6,<2.0a0
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - python >=3.7,<3.8.0a0
        - qt 5.9.*
        - qt >=5.9.7,<5.10.0a0
        - sip >=4.19.4,<=4.19.8
test:
    commands:
        - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'python pyqt_test.py'
    files:
        - pyqt_test.py
    imports:
        - PyQt5.QtCore
        - PyQt5.QtGui
        - PyQt5.QtHelp
        - PyQt5.QtMultimedia
        - PyQt5.QtMultimediaWidgets
        - PyQt5.QtNetwork
        - PyQt5.QtOpenGL
        - PyQt5.QtPrintSupport
        - PyQt5.QtQml
        - PyQt5.QtQuick
        - PyQt5.QtSvg
        - PyQt5.QtTest
        - PyQt5.QtWebChannel
        - PyQt5.QtWebEngineWidgets
        - PyQt5.QtWebSockets
        - PyQt5.QtWidgets
        - PyQt5.QtXml
        - PyQt5.QtXmlPatterns
about:
    description: '"PyQt is a set of Python v2 and v3 bindings for The Qt Company''s
        Qt

        application framework and runs on all platforms supported by Qt including

        Windows, MacOS/X and Linux. PyQt5 supports Qt v5. PyQt4 supports Qt v4 and

        will build against Qt v5. The bindings are implemented as a set of Python

        modules and contain over 1,000 classes."

        '
    dev_url: https://github.com/pyqt
    doc_url: https://www.riverbankcomputing.com/software/pyqt/
    home: http://www.riverbankcomputing.co.uk/software/pyqt
    license: Commercial, GPL-2.0, GPL-3.0
    license_family: GPL
    license_file: LICENSE
    summary: Python binding of the cross-platform GUI toolkit Qt.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - gillins
        - jschueller
        - mingwandroid
        - msarahan
        - ocefpaf
