# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Dec  1 09:47:05 2019
# ------------------------------------------------

package:
    name: openjpeg
    version: 2.3.1
source:
    sha256: 63f5a4713ecafc86de51bfad89cc07bb788e9bba24ebbf0c4ca637621aadb6a9
    url: https://github.com/uclouvain/openjpeg/archive/v2.3.1.tar.gz
build:
    number: '3'
    run_exports:
        - openjpeg >=2.3.1,<3.0a0
    string: h981e76c_3
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he1b5a44_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - bzip2 1.0.8 h516909a_1
        - ca-certificates 2019.11.28 hecc5488_0
        - cmake 3.15.5 hf94ab9c_0
        - curl 7.65.3 hf8cf82a_0
        - expat 2.2.5 he1b5a44_1004
        - gcc_impl_linux-64 7.3.0 habb00fd_2
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_2
        - gxx_linux-64 7.3.0 h553295d_15
        - krb5 1.16.3 h05b26f9_1001
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libcurl 7.65.3 hda55be3_0
        - libedit 3.1.20170329 hf8c457e_1001
        - libgcc-ng 9.2.0 hdf63c60_0
        - libssh2 1.8.2 h22169c7_2
        - libstdcxx-ng 9.2.0 hdf63c60_0
        - libuv 1.33.1 h516909a_0
        - make 4.2.1 h14c3975_2004
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1d h516909a_0
        - rhash 1.3.6 h14c3975_1001
        - tk 8.6.10 hed695b0_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1006
    host:
        - _libgcc_mutex 0.1 main
        - jpeg 9c h14c3975_1001
        - libgcc-ng 9.2.0 hdf63c60_0
        - libpng 1.6.37 hed695b0_0
        - libstdcxx-ng 9.2.0 hdf63c60_0
        - libtiff 4.1.0 hc3755c2_1
        - lz4-c 1.8.3 he1b5a44_1001
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1006
        - zstd 1.4.4 h3b9ef0a_1
    run:
        - libgcc-ng >=7.3.0
        - libpng >=1.6.37,<1.7.0a0
        - libpng >=1.6.37,<1.7.0a0
        - libstdcxx-ng >=7.3.0
        - libtiff >=4.1.0,<5.0a0
        - libtiff >=4.1.0,<5.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - opj_dump -i p0_01.j2k
    files:
        - p0_01.j2k
about:
    home: http://www.openjpeg.org/
    license: BSD-2-Clause
    license_file: LICENSE
    summary: An open-source JPEG 2000 codec written in C
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - gillins
        - mingwandroid
        - ocefpaf
