# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Oct 14 01:52:13 2020
# ------------------------------------------------

package:
    name: ipython
    version: 7.18.1
source:
    sha256: a331e78086001931de9424940699691ad49dfb457cea31f5471eae7b78222d5e
    url: https://pypi.io/packages/source/i/ipython/ipython-7.18.1.tar.gz
build:
    entry_points:
        - iptest = IPython.testing.iptestcontroller:main
        - iptest3 = IPython.testing.iptestcontroller:main
        - ipython = IPython:start_ipython
        - ipython3 = IPython:start_ipython
    number: '1'
    script: /home/conda/feedstock_root/build_artifacts/ipython_1602640393953/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
        -m pip install . -vv
    string: py37hc6149b9_1
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py37he5f6b98_2
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 he1b5a44_2
        - openssl 1.1.1h h516909a_0
        - pip 20.2.3 py_0
        - python 3.7.8 h6f2ec95_1_cpython
        - python_abi 3.7 1_cp37m
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py37he5f6b98_2
        - sqlite 3.33.0 h4cf870e_1
        - tk 8.6.10 hed695b0_1
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1009
    run:
        - backcall
        - decorator
        - jedi >=0.10
        - pexpect >4.3
        - pickleshare
        - prompt-toolkit !=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
        - pygments
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
        - setuptools >=18.5
        - traitlets >=4.2
test:
    commands:
        - ipython -h
        - ipython3 -h
        - NOSE_EXCLUDE="recursion|test_set_matplotlib_formats|test_set_matplotlib_close|test_history|system_interrupt"
            iptest
        - python -m pip check
    imports:
        - IPython
        - IPython.core
        - IPython.core.magics
        - IPython.core.tests
        - IPython.extensions
        - IPython.extensions.tests
        - IPython.external
        - IPython.external.decorators
        - IPython.lib
        - IPython.lib.tests
        - IPython.sphinxext
        - IPython.terminal
        - IPython.terminal.pt_inputhooks
        - IPython.terminal.tests
        - IPython.testing
        - IPython.testing.plugin
        - IPython.testing.tests
        - IPython.utils
        - IPython.utils.tests
    requires:
        - curio
        - matplotlib-base
        - nbformat
        - nose >=0.10.1
        - numpy
        - pip
        - pygments
        - requests
        - testpath
        - trio
about:
    description: 'IPython provides a rich architecture for interactive computing with

        a powerful interactive shell, a kernel for Jupyter, high performance

        tools for parallel computing, and more.

        '
    dev_url: https://github.com/ipython/ipython
    doc_url: https://ipython.readthedocs.io
    home: https://ipython.org
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: 'IPython: Productive Interactive Computing'
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Carreau
        - blink1073
        - bollwyvl
        - ellisonbg
        - fperez
        - jakirkham
        - minrk
        - ocefpaf
        - pelson
        - takluyver
