# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /opt/recipe, last modified Wed Mar 13 22:22:16 2019
# ------------------------------------------------

package:
    name: perl-xml-simple
    version: '2.25'
source:
    sha256: 531fddaebea2416743eb5c4fdfab028f502123d9a220405a4100e68fc480dbf8
    url: https://cpan.metacpan.org/authors/id/G/GR/GRANTM/XML-Simple-2.25.tar.gz
build:
    number: '1'
    string: pl526_1
requirements:
    host:
        - expat 2.2.5 hf484d3e_1002
        - libgcc-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 7.3.0 hdf63c60_0
        - perl 5.26.2 h14c3975_1002
        - perl-app-cpanminus 1.7044 pl526_1
        - perl-carp 1.38 pl526_2
        - perl-constant 1.33 pl526_1
        - perl-exporter 5.72 pl526_1
        - perl-extutils-makemaker 7.34 pl526_3
        - perl-file-path 2.15 pl526_0
        - perl-file-temp 0.2304 pl526_2
        - perl-parent 0.236 pl526_1
        - perl-xml-namespacesupport 1.12 pl526_0
        - perl-xml-parser 2.44_01 pl526h3a4f0e9_1
        - perl-xml-sax 1.00 pl526_0
        - perl-xml-sax-base 1.09 pl526_0
        - perl-xml-sax-expat 0.51 pl526_3
    run:
        - perl >=5.26.2,<5.26.3.0a0
        - perl-xml-namespacesupport
        - perl-xml-sax
        - perl-xml-sax-expat
test:
    imports:
        - XML::Simple
about:
    home: http://metacpan.org/pod/XML-Simple
    license: perl_5
    summary: An API for simple XML files
extra:
    copy_test_source_files: true
    final: true
