# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jan  6 02:47:30 2020
# ------------------------------------------------

package:
    name: libwebp
    version: 1.0.2
source:
    fn: libwebp-1.0.2.tar.gz
    sha256: 3d47b48c40ed6476e8047b2ddb81d93835e0ca1b8d3e8c679afbb3004dd564b1
    url: http://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.0.2.tar.gz
build:
    number: '5'
    run_exports:
        - libwebp >=1.0.2,<1.1.0a0
    string: h56121f0_5
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he1b5a44_7
        - binutils_linux-64 2.33.1 h9595d00_16
        - gcc_impl_linux-64 7.3.0 habb00fd_2
        - gcc_linux-64 7.3.0 h553295d_16
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.2.0 hdf63c60_0
        - libstdcxx-ng 9.2.0 hdf63c60_0
        - make 4.2.1 h14c3975_2004
    host:
        - _libgcc_mutex 0.1 main
        - giflib 5.2.1 h516909a_1
        - jpeg 9c h14c3975_1001
        - libgcc-ng 9.2.0 hdf63c60_0
        - libpng 1.6.37 hed695b0_0
        - libstdcxx-ng 9.2.0 hdf63c60_0
        - libtiff 4.1.0 hc3755c2_3
        - lz4-c 1.8.3 he1b5a44_1001
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1006
        - zstd 1.4.4 h3b9ef0a_1
    run:
        - giflib >=5.2.1,<5.3.0a0
        - jpeg >=9c,<10a
        - jpeg >=9c,<10a
        - libgcc-ng >=7.3.0
        - libpng >=1.6.37,<1.7.0a0
        - libpng >=1.6.37,<1.7.0a0
        - libtiff >=4.1.0,<5.0a0
        - libtiff >=4.1.0,<5.0a0
test:
    commands:
        - test -f $PREFIX/lib/libwebp.a
        - test -f $PREFIX/lib/libwebp.so
        - test -f $PREFIX/bin/cwebp
        - test -f $PREFIX/bin/dwebp
        - test -f $PREFIX/include/webp/decode.h
        - test -f $PREFIX/include/webp/encode.h
        - test -f $PREFIX/include/webp/types.h
about:
    description: 'WebP is a method of lossy and lossless compression that can be used
        on a large variety of photographic,

        translucent and graphical images found on the web. The degree of lossy compression
        is adjustable so a

        user can choose the trade-off between file size and image quality.

        '
    dev_url: https://chromium.googlesource.com/webm/libwebp
    doc_url: https://developers.google.com/speed/webp/docs/using
    home: https://developers.google.com/speed/webp/
    license: Google
    license_file: COPYING
    summary: WebP image library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dschreij
