# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Sep 18 18:38:42 2020
# ------------------------------------------------

package:
    name: bleach
    version: 3.2.1
source:
    sha256: 52b5919b81842b1854196eaae5ca29679a2f2e378905c346d3ca8227c2c66080
    url: https://pypi.io/packages/source/b/bleach/bleach-3.2.1.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/bleach_1600454382015/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . -vvv
    string: pyh9f0ad1d_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py36h9f0ad1d_0
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libstdcxx-ng 9.3.0 hdf63c60_16
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1g h516909a_1
        - pip 20.2.3 py_0
        - python 3.6.11 h4d41432_2_cpython
        - python_abi 3.6 1_cp36m
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py36h9f0ad1d_1
        - sqlite 3.33.0 h4cf870e_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1009
    run:
        - packaging
        - python
        - setuptools
        - six
        - webencodings
test:
    commands:
        - pip check
    imports:
        - bleach
    requires:
        - pip
about:
    description: 'Bleach is an allowed-list-based HTML sanitizing library that escapes
        or

        strips markup and attributes.

        '
    dev_url: https://github.com/mozilla/bleach
    doc_source_url: https://github.com/mozilla/bleach/blob/master/docs/index.rst
    doc_url: https://bleach.readthedocs.io/
    home: https://github.com/mozilla/bleach
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
    summary: Easy, whitelist-based HTML-sanitizing tool
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - minrk
        - ocefpaf
