# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /opt/recipe, last modified Sun Jul 15 05:00:50 2018
# ------------------------------------------------

package:
    name: perl-socket
    version: '2.027'
source:
    sha256: 141c11494d171c13765d972417be731388f6372ffaad619cfc72998e972be2a8
    url: https://cpan.metacpan.org/authors/id/P/PE/PEVANS/Socket-2.027.tar.gz
build:
    number: '1'
    string: pl526_1
requirements:
    host:
        - libgcc-ng 7.2.0 hdf63c60_3
        - perl 5.26.2 h470a237_0
        - perl-app-cpanminus 1.7044 pl526_0
        - perl-carp 1.38 pl526_1
        - perl-constant 1.33 pl526_1
        - perl-devel-symdump 2.18 pl526_1
        - perl-exporter 5.72 pl526_1
        - perl-extutils-cbuilder 0.280230 pl526_1
        - perl-extutils-constant 0.24 pl526_1
        - perl-extutils-makemaker 7.34 pl526_0
        - perl-file-path 2.12 pl526_1
        - perl-file-temp 0.2304 pl526_2
        - perl-ipc-cmd 1.02 pl526_0
        - perl-list-util 1.38 pl526_1
        - perl-locale-maketext-simple 0.21 pl526_1
        - perl-module-corelist 5.20180120 pl526_1
        - perl-module-load 0.32 pl526_1
        - perl-module-load-conditional 0.68 pl526_2
        - perl-module-metadata 1.000019 pl526_1
        - perl-params-check 0.38 pl526_1
        - perl-parent 0.236 pl526_1
        - perl-perl-ostype 1.010 pl526_1
        - perl-scalar-list-utils 1.45 pl526h470a237_3
        - perl-test-more 1.001002 pl526_1
        - perl-text-parsewords 3.29 pl526_3
        - perl-version 0.9924 pl526_0
    run:
        - perl >=5.26.2,<5.27.0a0
test:
    imports:
        - Socket
about:
    home: http://metacpan.org/pod/Socket
    license: perl_5
    summary: networking constants and support functions
extra:
    copy_test_source_files: true
    final: true
