# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /opt/recipe, last modified Mon Dec 17 22:50:26 2018
# ------------------------------------------------

package:
    name: perl-data-dumper
    version: '2.173'
source:
    sha256: 697608b39330988e519131be667ff47168aaaaf99f06bd2095d5b46ad05d76fa
    url: https://cpan.metacpan.org/authors/id/X/XS/XSAWYERX/Data-Dumper-2.173.tar.gz
build:
    number: '0'
    string: pl526_0
requirements:
    host:
        - libgcc-ng 7.2.0 hdf63c60_3
        - perl 5.26.2 h470a237_0
        - perl-extutils-makemaker 7.34 pl526_3
    run:
        - perl >=5.26.2,<5.26.3.0a0
test:
    imports:
        - Data::Dumper
about:
    home: http://metacpan.org/pod/Data::Dumper
    license: unknown
    summary: seeds germane, yet not germinated
extra:
    copy_test_source_files: true
    final: true
