# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Feb 22 11:22:51 2020
# ------------------------------------------------

package:
    name: giflib
    version: 5.2.1
source:
    -   patches: null
        sha256: 31da5562f44c5f15d63340a09a4fd62b48c45620cd302f77a6d9acf0077879bd
        url: http://downloads.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz
build:
    number: '2'
    run_exports:
        - giflib >=5.2.1,<5.3.0a0
    string: h516909a_2
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - binutils_impl_linux-64 2.33.1 h53a641e_8
        - binutils_linux-64 2.33.1 h9595d00_16
        - bzip2 1.0.8 h516909a_2
        - ca-certificates 2019.11.28 hecc5488_0
        - cmake 3.16.4 h28c56e5_0
        - expat 2.2.9 he1b5a44_2
        - gcc_impl_linux-64 7.3.0 hd420e75_5
        - gcc_linux-64 7.3.0 h553295d_16
        - krb5 1.16.4 h2fd8d38_0
        - ld_impl_linux-64 2.33.1 h53a641e_8
        - libcurl 7.68.0 hda55be3_0
        - libedit 3.1.20170329 hf8c457e_1001
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libssh2 1.8.2 h22169c7_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - libuv 1.34.0 h516909a_0
        - make 4.2.1 h14c3975_2004
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1d h516909a_0
        - rhash 1.3.6 h14c3975_1001
        - tk 8.6.10 hed695b0_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1006
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
    run:
        - libgcc-ng >=7.3.0
test:
    commands:
        - gif2rgb -h
        - gifbuild -h
        - giffix -h
        - giftext -h
        - gifclrmp -h
about:
    home: http://giflib.sourceforge.net
    license: MIT
    license_file:
        - COPYING
    summary: Library for reading and writing gif images
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - 183amir
        - isuruf
        - msarahan
        - ocefpaf
        - wolfv
