# This file created by conda-build 3.12.1
# meta.yaml template originally from:
# /opt/recipe, last modified Fri Aug 24 03:03:38 2018
# ------------------------------------------------

package:
    name: perl-business-isbn-data
    version: '20140910.003'
source:
    sha256: c756048c9b2b76ae5a7b9f1e1f6c59af670ff89b1fa574d4c3d7e4c9659685c9
    url: https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Business-ISBN-Data-20140910.003.tar.gz
build:
    number: '0'
    string: pl526_0
requirements:
    host:
        - libgcc-ng 7.2.0 hdf63c60_3
        - perl 5.26.2 h470a237_0
        - perl-carp 1.38 pl526_1
        - perl-data-dumper 2.161 pl526_2
        - perl-encode 2.88 pl526_1
        - perl-exporter 5.72 pl526_1
        - perl-extutils-makemaker 7.34 pl526_2
        - perl-parent 0.236 pl526_1
    run:
        - perl >=5.26.2,<5.26.3.0a0
        - perl-carp
test:
    imports:
        - Business::ISBN::Data
about:
    home: https://github.com/briandfoy/business-isbn-data
    license: perl_5
    summary: data pack for Business::ISBN
extra:
    copy_test_source_files: true
    final: true
